const QUERY_KEYS = {
  REGISTER: "REGISTER",
  RESEND_EMAIL_OTP: "RESEND_EMAIL_OTP",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  LOGIN: "LOGIN",
  REQUEST_PASSWORD_CHANGE_EMAIL_OTP: "REQUEST_PASSWORD_CHANGE_EMAIL_OTP",
  RESET_PASSWORD_WITH_EMAIL: "RESET_PASSWORD_WITH_EMAIL",
  AUTH_CONFIG: "AUTH_CONFIG",
  GET_SLIDES: "GET_SLIDES",
  GET_SONGS_LATEST_RELEASE: "GET_SONGS_LATEST_RELEASE",
  GET_HERO_ARTISTS: "GET_HERO_ARTISTS",
  GET_LATEST_SONGS_FROM_HISTORY: "GET_LATEST_SONGS_FROM_HISTORY",
  LATEST_PLAYLISTS: "LATEST_PLAYLISTS",
  GLOBAL_SEARCH: "GLOBAL_SEARCH",
  FILTER: "FILTER",
  FILTER_ARTISTS: "FILTER_ARTISTS",
  FILTER_ALBUMS: "FILTER_ALBUMS",

  CREATE_PLAYLIST: "CREATE_PLAYLIST",
  GET_PLAYLISTS: "GET_PLAYLISTS",
  ADD_SONGS_IN_PLAYLIST: "ADD_SONGS_IN_PLAYLIST",
  GET_PLAYLIST_SONGS: "GET_PLAYLIST_SONGS",

  ADD_REQUEST_TO_ADD_SONG: "ADD_REQUEST_TO_ADD_SONG",
};

export default QUERY_KEYS;
