const QUERY_KEYS = {
  REGISTER: "REGISTER",
  RESEND_EMAIL_OTP: "RESEND_EMAIL_OTP",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  LOGIN: "LOGIN",
  REQUEST_PASSWORD_CHANGE_EMAIL_OTP: "REQUEST_PASSWORD_CHANGE_EMAIL_OTP",
  RESET_PASSWORD_WITH_EMAIL: "RESET_PASSWORD_WITH_EMAIL",
  AUTH_CONFIG: "AUTH_CONFIG",
};

export default QUERY_KEYS;
